### ISSUE TITLE
The Definition and the Completion don't work on Ruby 2.2

### ISSUE THREAD

**Issue by steiley** [mtsmfm/language_server-ruby#44]
I encountered the following error  when trying to start the Definition or the Completion.

```
NoMethodError: undefined method `fetch_values' for {:line=>80, :character=>33}:Hash
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/language_server-0.9.0/lib/language_server.rb:137:in `block in <module:LanguageServer>'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/language_server-0.9.0/lib/language_server.rb:46:in `call'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/language_server-0.9.0/lib/language_server.rb:46:in `block in run'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/language_server-protocol-0.4.0/lib/language_server/protocol/transport/stdio/reader.rb:27:in `call'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/language_server-protocol-0.4.0/lib/language_server/protocol/transport/stdio/reader.rb:27:in `read'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/language_server-0.9.0/lib/language_server.rb:35:in `run'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/language_server-0.9.0/exe/language_server-ruby:8:in `<top (required)>'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/bin/language_server-ruby:23:in `load'
  /home/steiley/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/bin/language_server-ruby:23:in `<top (required)>'
```

Actually there is no function called fetcth_values ​​in the Hash class of Ruby ​​2.2.
But I think It is not necessary to implement fetch_values for Ruby ​​2.2.
How about removing Ruby ​​2.2 from support?

**Comment by mtsmfm** [comment]
Wow, sorry the coverage isn't enough 🙇 
I'd like to support Ruby 2.2 until EOL. (It will be this December though)
So I'll add test and fix this problem.

**Comment by steiley** [comment]
I see.
I understand that.

**Comment by mathieujobin** [comment]
does that means this never worked?

**Comment by mtsmfm** [comment]
@mathieujobin 
Sorry, I haven't fixed this problem before Ruby 2.2 EOL.
Are you still using 2.2?
